version: 0.2

env:
  variables:
    NODE_ENV: "${env}"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm i
  pre_build:
    commands:
      - npm i
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed on

artifacts:
  files:
    - "build/*"
  name: "web-dist-${env}"
  base-directory: build

cache:
  paths:
    - /root/.npm/**/*
